// <auto-generated />
using System;
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(AppDbCon))]
    [Migration("20250801054315_IlkOlusturma")]
    partial class IlkOlusturma
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Cinsiyet", b =>
                {
                    b.Property<int>("CinsiyetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CinsiyetId"));

                    b.Property<string>("CinsiyetAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CinsiyetId");

                    b.ToTable("Cinsiyet");
                });

            modelBuilder.Entity("Entities.DoktorKabulDurumu", b =>
                {
                    b.Property<int>("DoktorKabulDurumuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DoktorKabulDurumuId"));

                    b.Property<int>("AlinanKabulSayisi")
                        .HasColumnType("int");

                    b.Property<int>("HekimId")
                        .HasColumnType("int");

                    b.Property<int>("MisafirKabulSayisi")
                        .HasColumnType("int");

                    b.Property<int>("ToplamKayitliHastaSayisi")
                        .HasColumnType("int");

                    b.HasKey("DoktorKabulDurumuId");

                    b.HasIndex("HekimId");

                    b.ToTable("DoktorKabulDurumu");
                });

            modelBuilder.Entity("Entities.DoktorKayit", b =>
                {
                    b.Property<int>("HekimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HekimId"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CinsiyetId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Dogumtarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Yas")
                        .HasColumnType("int");

                    b.HasKey("HekimId");

                    b.HasIndex("CinsiyetId");

                    b.ToTable("DoktorKayit");
                });

            modelBuilder.Entity("Entities.KabulListe", b =>
                {
                    b.Property<int>("KabulId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KabulId"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Dogumtarih")
                        .HasColumnType("datetime2");

                    b.Property<int>("HekimId")
                        .HasColumnType("int");

                    b.Property<bool>("OncelikliMi")
                        .HasColumnType("bit");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TamamlanmaDurumuId")
                        .HasColumnType("int");

                    b.Property<string>("Tc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Yas")
                        .HasColumnType("int");

                    b.HasKey("KabulId");

                    b.HasIndex("HekimId");

                    b.HasIndex("TamamlanmaDurumuId");

                    b.ToTable("KabulListe");
                });

            modelBuilder.Entity("Entities.KayitliKisiListe", b =>
                {
                    b.Property<int>("KayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KayId"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AnneAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BabaAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Dogumtarih")
                        .HasColumnType("datetime2");

                    b.Property<int>("HekimId")
                        .HasColumnType("int");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Yas")
                        .HasColumnType("int");

                    b.HasKey("KayId");

                    b.HasIndex("HekimId");

                    b.ToTable("KayitliKisiListesi");
                });

            modelBuilder.Entity("Entities.MhrsKayit", b =>
                {
                    b.Property<int>("MhrsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MhrsId"));

                    b.Property<string>("Ad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HekimId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Saat")
                        .HasColumnType("time");

                    b.Property<string>("Soyad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("Tc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MhrsId");

                    b.HasIndex("HekimId");

                    b.ToTable("MhrsKayit");
                });

            modelBuilder.Entity("Entities.Misafir", b =>
                {
                    b.Property<int>("MisafirId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MisafirId"));

                    b.Property<int>("HekimId")
                        .HasColumnType("int");

                    b.Property<string>("Tc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MisafirId");

                    b.HasIndex("HekimId");

                    b.ToTable("Misafir");
                });

            modelBuilder.Entity("Entities.TamamlanmaDurumu", b =>
                {
                    b.Property<int>("TamamlanmaDurumuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TamamlanmaDurumuId"));

                    b.Property<string>("DurumAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TamamlanmaDurumuId");

                    b.ToTable("TamamlanmaDurumu");
                });

            modelBuilder.Entity("Entities.DoktorKabulDurumu", b =>
                {
                    b.HasOne("Entities.DoktorKayit", "Hekim")
                        .WithMany("DoktorKabulDurumlari")
                        .HasForeignKey("HekimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hekim");
                });

            modelBuilder.Entity("Entities.DoktorKayit", b =>
                {
                    b.HasOne("Entities.Cinsiyet", "Cinsiyet")
                        .WithMany("Doktorlar")
                        .HasForeignKey("CinsiyetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cinsiyet");
                });

            modelBuilder.Entity("Entities.KabulListe", b =>
                {
                    b.HasOne("Entities.DoktorKayit", "Hekim")
                        .WithMany("KabulListeleri")
                        .HasForeignKey("HekimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.TamamlanmaDurumu", "TamamlanmaDurumu")
                        .WithMany("KabulListeleri")
                        .HasForeignKey("TamamlanmaDurumuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hekim");

                    b.Navigation("TamamlanmaDurumu");
                });

            modelBuilder.Entity("Entities.KayitliKisiListe", b =>
                {
                    b.HasOne("Entities.DoktorKayit", "Hekim")
                        .WithMany("KayitliKisiler")
                        .HasForeignKey("HekimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hekim");
                });

            modelBuilder.Entity("Entities.MhrsKayit", b =>
                {
                    b.HasOne("Entities.DoktorKayit", "Hekim")
                        .WithMany("MhrsKayitlar")
                        .HasForeignKey("HekimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hekim");
                });

            modelBuilder.Entity("Entities.Misafir", b =>
                {
                    b.HasOne("Entities.DoktorKayit", "Hekim")
                        .WithMany("Misafirler")
                        .HasForeignKey("HekimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hekim");
                });

            modelBuilder.Entity("Entities.Cinsiyet", b =>
                {
                    b.Navigation("Doktorlar");
                });

            modelBuilder.Entity("Entities.DoktorKayit", b =>
                {
                    b.Navigation("DoktorKabulDurumlari");

                    b.Navigation("KabulListeleri");

                    b.Navigation("KayitliKisiler");

                    b.Navigation("MhrsKayitlar");

                    b.Navigation("Misafirler");
                });

            modelBuilder.Entity("Entities.TamamlanmaDurumu", b =>
                {
                    b.Navigation("KabulListeleri");
                });
#pragma warning restore 612, 618
        }
    }
}
